import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:mosaic_sdk/mosaic_sdk.dart';

import 'support/canonical_fixture.dart';

/// Drives every frame the canonical Protocol 0.4 conformance corpus records
/// through this SDK's frame math.
///
/// Motion is the first thing in the protocol whose contract is a *value at an
/// instant* rather than a value, and three renderers will not agree by
/// coincidence. The vectors are generated by the reference resolver and
/// reconciled against it by the protocol gate, so this test is the Flutter side
/// of that reconciliation. Values are read from the repository fixture rather
/// than transcribed here: a copied expectation stops being a conformance check
/// the moment the corpus is regenerated.
void main() {
  final vectors = jsonDecode(
    repositoryFile('protocol/fixtures/v0.4/motion-frames.json')
        .readAsStringSync(),
  )! as Map<String, Object?>;
  final tolerance = (vectors['toleranceAbsolute']! as num).toDouble();
  final cases =
      (vectors['cases']! as List<Object?>).cast<Map<String, Object?>>();

  test('easing presets carry the normative control points', () {
    final recorded = vectors['easingControlPoints']! as Map<String, Object?>;
    expect(
      recorded.keys.toSet(),
      MosaicMotionEasing.values.map((easing) => easing.name).toSet(),
      reason: 'the SDK and the corpus must name the same four presets',
    );
    for (final entry in recorded.entries) {
      final easing = MosaicMotionEasing.values.byName(entry.key);
      final points = (entry.value! as List<Object?>)
          .map((value) => (value! as num).toDouble())
          .toList();
      expect(
        mosaicMotionEasingControlPoints[easing],
        (points[0], points[1], points[2], points[3]),
        reason: '$easing control points are normative and fixture-pinned',
      );
    }
  });

  test('reproduces every recorded motion frame within the stated tolerance',
      () {
    expect(cases, isNotEmpty, reason: 'the corpus must not be empty');
    var frameCount = 0;
    final triggers = <String>{};

    for (final entry in cases) {
      final id = entry['id']! as String;
      final trigger = entry['trigger']! as String;
      final reducedMotion = entry['reducedMotion']! as bool;
      final motion = entry['motion']! as Map<String, Object?>;
      triggers.add(trigger);

      for (final value in (entry['frames']! as List<Object?>)) {
        final record = value! as Map<String, Object?>;
        final elapsed = (record['elapsedMilliseconds']! as num).toInt();
        final expected = record['frame']! as Map<String, Object?>;
        final reason = 'case $id at ${elapsed}ms';
        frameCount += 1;

        switch (trigger) {
          case 'appear':
            final actual = resolveMosaicAppearFrame(
              _appearMotion(motion),
              elapsedMilliseconds: elapsed,
              reducedMotion: reducedMotion,
            );
            expect(actual.complete, expected['complete'], reason: reason);
            _near(actual.progress, expected['progress'], tolerance, reason);
            _near(actual.opacity, expected['opacity'], tolerance, reason);
            _near(
              actual.translateLogicalSize,
              expected['translateLogicalSize'],
              tolerance,
              reason,
            );
          case 'selection':
            final actual = resolveMosaicSelectionFrame(
              _selectionMotion(motion),
              elapsedMilliseconds: elapsed,
              reducedMotion: reducedMotion,
              resolvedFrom:
                  _style(entry['resolvedFrom']! as Map<String, Object?>),
              resolvedTo: _style(entry['resolvedTo']! as Map<String, Object?>),
            );
            expect(actual.complete, expected['complete'], reason: reason);
            _near(actual.progress, expected['progress'], tolerance, reason);
            _expectStyle(
              actual.style,
              expected['style']! as Map<String, Object?>,
              tolerance,
              reason,
            );
          case 'loop':
            final actual = resolveMosaicLoopFrame(
              _loopMotion(motion),
              elapsedMilliseconds: elapsed,
              reducedMotion: reducedMotion,
            );
            expect(actual.complete, expected['complete'], reason: reason);
            expect(actual.cycle, expected['cycle'], reason: reason);
            _near(actual.cyclePhase, expected['cyclePhase'], tolerance, reason);
            _near(actual.excursion, expected['excursion'], tolerance, reason);
            _near(actual.scale, expected['scale'], tolerance, reason);
            _near(
              actual.opacityMultiplier,
              expected['opacityMultiplier'],
              tolerance,
              reason,
            );
          default:
            fail('unknown trigger $trigger in case $id');
        }
      }
    }

    // A truncated corpus would otherwise report perfect conformance over
    // nothing, so the count and the trigger coverage are asserted rather than
    // assumed.
    expect(triggers, <String>{'appear', 'selection', 'loop'});
    expect(frameCount, 229);
  });

  test('the last frame of every case is the terminal state', () {
    // This is the rule that makes rendering without motion lossless: what a
    // motion-less renderer draws is what a motion-capable one ends at.
    for (final entry in cases) {
      final frames =
          (entry['frames']! as List<Object?>).cast<Map<String, Object?>>();
      final terminal = frames.last['frame']! as Map<String, Object?>;
      expect(
        terminal['complete'],
        isTrue,
        reason: 'case ${entry['id']} never reaches its terminal state',
      );
    }
  });

  test('a resolver refuses an unresolved token and a negative clock', () {
    // A resolver that accepted an unresolvable token would return the frame for
    // a duration nobody authored, and one that accepted a bad clock would
    // return a frame that reads back as plausible.
    const unresolved = MosaicAppearMotion(
      effect: MosaicAppearEffect.fade,
      curve: MosaicMotionTokenReference('motion-entrance'),
      delayMilliseconds: 0,
    );
    expect(
      () => resolveMosaicAppearFrame(
        unresolved,
        elapsedMilliseconds: 0,
        reducedMotion: false,
      ),
      throwsA(isA<MosaicMotionFrameException>()),
    );
    expect(
      () => resolveMosaicAppearFrame(
        const MosaicAppearMotion(
          effect: MosaicAppearEffect.fade,
          curve: MosaicInlineMotion(
            durationMilliseconds: 160,
            easing: MosaicMotionEasing.linear,
          ),
          delayMilliseconds: 0,
        ),
        elapsedMilliseconds: -1,
        reducedMotion: false,
      ),
      throwsA(isA<MosaicMotionFrameException>()),
    );
  });
}

void _near(double actual, Object? expected, double tolerance, String reason) {
  expect(
    actual,
    closeTo((expected! as num).toDouble(), tolerance),
    reason: reason,
  );
}

void _expectStyle(
  MosaicSelectionStateStyle actual,
  Map<String, Object?> expected,
  double tolerance,
  String reason,
) {
  final background = actual.background;
  expect(background, isA<MosaicColorBackground>(), reason: reason);
  expect(
    (background as MosaicColorBackground).color.value,
    (expected['background']! as Map<String, Object?>)['value'],
    reason: '$reason background',
  );
  final border = expected['border']! as Map<String, Object?>;
  expect(actual.border.color.value, border['color'], reason: '$reason border');
  _near(actual.border.width, border['width'], tolerance, '$reason borderWidth');
  _near(
    actual.cornerRadius,
    expected['cornerRadius'],
    tolerance,
    '$reason cornerRadius',
  );
  _near(actual.opacity, expected['opacity'], tolerance, '$reason opacity');

  final padding = expected['padding']! as Map<String, Object?>;
  _near(actual.padding.top, padding['top'], tolerance, '$reason padding.top');
  _near(
    actual.padding.start,
    padding['start'],
    tolerance,
    '$reason padding.start',
  );
  _near(
    actual.padding.bottom,
    padding['bottom'],
    tolerance,
    '$reason padding.bottom',
  );
  _near(actual.padding.end, padding['end'], tolerance, '$reason padding.end');

  final shadow = expected['shadow'] as Map<String, Object?>?;
  if (shadow == null) {
    expect(actual.shadow, isNull, reason: '$reason shadow');
    return;
  }
  expect(actual.shadow, isA<MosaicInlineShadow>(), reason: '$reason shadow');
  final resolved = actual.shadow! as MosaicInlineShadow;
  expect(resolved.color.value, shadow['color'], reason: '$reason shadowColor');
  _near(resolved.offsetX, shadow['offsetX'], tolerance, '$reason shadowX');
  _near(resolved.offsetY, shadow['offsetY'], tolerance, '$reason shadowY');
  _near(resolved.blurRadius, shadow['blurRadius'], tolerance, '$reason blur');
}

MosaicAppearMotion _appearMotion(Map<String, Object?> motion) =>
    MosaicAppearMotion(
      effect: motion['effect'] == 'fadeRise'
          ? MosaicAppearEffect.fadeRise
          : MosaicAppearEffect.fade,
      riseLogicalSize: (motion['riseLogicalSize'] as num?)?.toDouble(),
      curve: _curve(motion['curve']! as Map<String, Object?>),
      delayMilliseconds: (motion['delayMilliseconds']! as num).toInt(),
    );

MosaicSelectionMotion _selectionMotion(Map<String, Object?> motion) =>
    MosaicSelectionMotion(
      curve: _curve(motion['curve']! as Map<String, Object?>),
    );

MosaicLoopMotion _loopMotion(Map<String, Object?> motion) => MosaicLoopMotion(
      effect: MosaicLoopEffect.pulse,
      scaleAmplitude: (motion['scaleAmplitude']! as num).toDouble(),
      opacityAmplitude: (motion['opacityAmplitude']! as num).toDouble(),
      curve: _curve(motion['curve']! as Map<String, Object?>),
      repeatCount:
          ((motion['repeat']! as Map<String, Object?>)['count']! as num)
              .toInt(),
    );

MosaicInlineMotion _curve(Map<String, Object?> curve) => MosaicInlineMotion(
      durationMilliseconds: (curve['durationMilliseconds']! as num).toInt(),
      easing: MosaicMotionEasing.values.byName(curve['easing']! as String),
    );

MosaicSelectionStateStyle _style(Map<String, Object?> style) {
  final border = style['border']! as Map<String, Object?>;
  final padding = style['padding']! as Map<String, Object?>;
  final shadow = style['shadow'] as Map<String, Object?>?;
  return MosaicSelectionStateStyle(
    background: MosaicColorBackground(
      MosaicColorValue.parse(
        (style['background']! as Map<String, Object?>)['value']! as String,
      ),
    ),
    border: MosaicBorderStyle(
      color: MosaicColorValue.parse(border['color']! as String),
      width: (border['width']! as num).toDouble(),
    ),
    cornerRadius: (style['cornerRadius']! as num).toDouble(),
    padding: MosaicEdgeInsets(
      top: (padding['top']! as num).toDouble(),
      start: (padding['start']! as num).toDouble(),
      bottom: (padding['bottom']! as num).toDouble(),
      end: (padding['end']! as num).toDouble(),
    ),
    opacity: (style['opacity']! as num).toDouble(),
    shadow: shadow == null
        ? null
        : MosaicInlineShadow(
            color: MosaicColorValue.parse(shadow['color']! as String),
            offsetX: (shadow['offsetX']! as num).toDouble(),
            offsetY: (shadow['offsetY']! as num).toDouble(),
            blurRadius: (shadow['blurRadius']! as num).toDouble(),
          ),
  );
}
