import Foundation
import XCTest

@testable import MosaicSDK

/// Drives every published Protocol 0.4 motion frame through the SDK's resolver.
///
/// Motion is the first thing in the protocol whose contract is a *value at an
/// instant* rather than a value, and three renderers will not agree by
/// coincidence. `protocol/fixtures/v0.4/motion-frames.json` is generated by the
/// reference resolver and reconciled against it by the protocol's own gate, so
/// reading it here is what binds this SDK to the same numbers Flutter, Compose,
/// and the browser preview are bound to. Copying the values into this target
/// instead would let Swift drift silently.
final class MotionConformanceTests: XCTestCase {

  /// Every frame of every case, within the fixture's own stated tolerance.
  ///
  /// Protects: cross-platform frame agreement. A bezier solved differently, a
  /// delay applied at the wrong end, an excursion that peaks off-centre, or a
  /// discrete field interpolated by mistake all fail here rather than shipping
  /// as a paywall that looks subtly different on one platform.
  func testEveryPublishedMotionFrameResolvesWithinTolerance() throws {
    let corpus = try motionFrameCorpus()
    var checkedFrames = 0

    for motionCase in corpus.cases {
      for frame in motionCase.frames {
        try assertFrame(
          frame,
          in: motionCase,
          tolerance: corpus.toleranceAbsolute
        )
        checkedFrames += 1
      }
    }

    XCTAssertEqual(
      checkedFrames, 229,
      "The published corpus carries 229 frames; a change in that count is a contract change."
    )
    XCTAssertEqual(corpus.cases.count, 45)
  }

  /// The control points are normative and fixture-pinned, and they are what the
  /// SwiftUI `timingCurve` animation is built from. If they drift, every
  /// platform-driven animation drifts with them while the frame math above still
  /// passes, so they are asserted against the fixture directly.
  func testEasingControlPointsMatchThePublishedValues() throws {
    let corpus = try motionFrameCorpus()
    XCTAssertEqual(corpus.easingControlPoints.count, MosaicMotionEasing.allCases.count)
    for easing in MosaicMotionEasing.allCases {
      let expected = try XCTUnwrap(corpus.easingControlPoints[easing.rawValue])
      let points = easing.controlPoints
      XCTAssertEqual([points.x1, points.y1, points.x2, points.y2], expected, "\(easing)")
    }
  }

  /// The last frame of every case is the terminal state, and the terminal state
  /// is the static rendering.
  ///
  /// Protects the one rule the whole enhancement tier rests on: a reader that
  /// cannot animate draws what an animating reader ends at. If any case ended
  /// anywhere else, `renderWithoutMotion` would silently be lossy.
  func testEveryCaseEndsAtTheStaticRendering() throws {
    for motionCase in try motionFrameCorpus().cases {
      let last = try XCTUnwrap(motionCase.frames.last)
      switch motionCase.trigger {
      case "appear":
        XCTAssertEqual(last.values["opacity"], 1, motionCase.id)
        XCTAssertEqual(last.values["translateLogicalSize"], 0, motionCase.id)
      case "loop":
        XCTAssertEqual(last.values["scale"], 1, motionCase.id)
        XCTAssertEqual(last.values["opacityMultiplier"], 1, motionCase.id)
      case "selection":
        XCTAssertEqual(last.style, motionCase.resolvedTo, motionCase.id)
      default:
        XCTFail("Unknown trigger \(motionCase.trigger)")
      }
      XCTAssertEqual(last.complete, true, motionCase.id)
    }
  }

  /// A clock the resolver cannot trust throws rather than resolving.
  ///
  /// Protects against the failure the contract calls out by name: arithmetic on
  /// a bad clock yields a frame that reads back as plausible, so a negative
  /// elapsed time must not quietly become frame zero.
  func testNegativeElapsedTimeThrowsRatherThanResolving() {
    let curve = MosaicResolvedMotionCurve(durationMilliseconds: 240, easing: .linear)
    let appear = MosaicAppearMotion(
      effect: .fade, riseLogicalSize: nil, curve: .inline(curve), delayMilliseconds: 0)
    XCTAssertThrowsError(
      try MosaicMotionResolver.appearFrame(
        appear, curve: curve, elapsedMilliseconds: -1, reducedMotion: false)
    ) { error in
      XCTAssertEqual(error as? MosaicMotionResolutionError, .invalidElapsedTime)
    }
  }

  // MARK: - Driving one frame

  private func assertFrame(
    _ frame: CorpusFrame,
    in motionCase: CorpusCase,
    tolerance: Double
  ) throws {
    let context = "\(motionCase.id) @ \(frame.elapsedMilliseconds)ms"
    let curve = try resolvedCurve(motionCase.motion, context: context)

    switch motionCase.trigger {
    case "appear":
      let motion = try decode(MosaicAppearMotion.self, from: motionCase.motion, context: context)
      let resolved = try MosaicMotionResolver.appearFrame(
        motion,
        curve: curve,
        elapsedMilliseconds: frame.elapsedMilliseconds,
        reducedMotion: motionCase.reducedMotion
      )
      assertClose(resolved.progress, frame.values["progress"], tolerance, "progress", context)
      assertClose(resolved.opacity, frame.values["opacity"], tolerance, "opacity", context)
      assertClose(
        resolved.translateLogicalSize, frame.values["translateLogicalSize"], tolerance,
        "translateLogicalSize", context)
      XCTAssertEqual(resolved.complete, frame.complete, "complete: \(context)")

    case "selection":
      let from = try XCTUnwrap(motionCase.resolvedFrom, context)
      let to = try XCTUnwrap(motionCase.resolvedTo, context)
      let resolved = try MosaicMotionResolver.selectionFrame(
        curve: curve,
        elapsedMilliseconds: frame.elapsedMilliseconds,
        reducedMotion: motionCase.reducedMotion,
        from: from,
        to: to
      )
      assertClose(resolved.progress, frame.values["progress"], tolerance, "progress", context)
      XCTAssertEqual(resolved.complete, frame.complete, "complete: \(context)")
      assertStyle(
        resolved.style, try XCTUnwrap(frame.style, context), tolerance, context)

    case "loop":
      let motion = try decode(MosaicLoopMotion.self, from: motionCase.motion, context: context)
      let resolved = try MosaicMotionResolver.loopFrame(
        motion,
        curve: curve,
        elapsedMilliseconds: frame.elapsedMilliseconds,
        reducedMotion: motionCase.reducedMotion
      )
      assertClose(resolved.cyclePhase, frame.values["cyclePhase"], tolerance, "cyclePhase", context)
      assertClose(resolved.excursion, frame.values["excursion"], tolerance, "excursion", context)
      assertClose(resolved.scale, frame.values["scale"], tolerance, "scale", context)
      assertClose(
        resolved.opacityMultiplier, frame.values["opacityMultiplier"], tolerance,
        "opacityMultiplier", context)
      XCTAssertEqual(Double(resolved.cycle), frame.values["cycle"], "cycle: \(context)")
      XCTAssertEqual(resolved.complete, frame.complete, "complete: \(context)")

    default:
      XCTFail("Unknown trigger \(motionCase.trigger)")
    }
  }

  private func assertClose(
    _ actual: Double,
    _ expected: Double?,
    _ tolerance: Double,
    _ field: String,
    _ context: String
  ) {
    guard let expected else { return XCTFail("\(context) has no \(field)") }
    XCTAssertEqual(actual, expected, accuracy: tolerance, "\(field): \(context)")
  }

  /// Colours are compared exactly and numbers within tolerance.
  ///
  /// A colour is either interpolated to a canonical literal or switched
  /// discretely, and both answers are exact: a colour that is "nearly" right is
  /// a colour the protocol did not specify.
  private func assertStyle(
    _ actual: MosaicSelectionStateStyle,
    _ expected: MosaicSelectionStateStyle,
    _ tolerance: Double,
    _ context: String
  ) {
    XCTAssertEqual(actual.background, expected.background, "background: \(context)")
    XCTAssertEqual(actual.border.color, expected.border.color, "border.color: \(context)")
    XCTAssertEqual(
      actual.border.width, expected.border.width, accuracy: tolerance,
      "border.width: \(context)")
    XCTAssertEqual(
      actual.cornerRadius, expected.cornerRadius, accuracy: tolerance,
      "cornerRadius: \(context)")
    XCTAssertEqual(actual.opacity, expected.opacity, accuracy: tolerance, "opacity: \(context)")
    // Padding switches discretely, so it must land on one authored value
    // exactly rather than somewhere between the two.
    XCTAssertEqual(actual.padding, expected.padding, "padding: \(context)")
    switch (actual.shadow, expected.shadow) {
    case (nil, nil):
      break
    case (.value(let a, let ax, let ay, let ab)?, .value(let e, let ex, let ey, let eb)?):
      XCTAssertEqual(a, e, "shadow.color: \(context)")
      XCTAssertEqual(ax, ex, accuracy: tolerance, "shadow.offsetX: \(context)")
      XCTAssertEqual(ay, ey, accuracy: tolerance, "shadow.offsetY: \(context)")
      XCTAssertEqual(ab, eb, accuracy: tolerance, "shadow.blurRadius: \(context)")
    default:
      XCTFail("shadow shape: \(context)")
    }
  }

  // MARK: - Reading the corpus

  private func resolvedCurve(_ motion: [String: Any], context: String) throws
    -> MosaicResolvedMotionCurve
  {
    let curve = try decode(
      MosaicMotionCurve.self, from: try XCTUnwrap(motion["curve"] as? [String: Any]),
      context: context)
    // The published cases carry inline curves only. A `motionToken` reference
    // has no duration until it is resolved against a document, and a resolver
    // that accepted one would return the frame for a duration nobody authored.
    guard case .inline(let resolved) = curve else {
      throw CanonicalFixtureLookupError.invalidShape
    }
    return resolved
  }

  private func decode<T: Decodable>(
    _ type: T.Type,
    from object: [String: Any],
    context: String
  ) throws -> T {
    try JSONDecoder().decode(type, from: JSONSerialization.data(withJSONObject: object))
  }

  private struct CorpusFrame {
    let elapsedMilliseconds: Int
    let complete: Bool
    let values: [String: Double]
    let style: MosaicSelectionStateStyle?
  }

  private struct CorpusCase {
    let id: String
    let trigger: String
    let reducedMotion: Bool
    let motion: [String: Any]
    let resolvedFrom: MosaicSelectionStateStyle?
    let resolvedTo: MosaicSelectionStateStyle?
    let frames: [CorpusFrame]
  }

  private struct Corpus {
    let toleranceAbsolute: Double
    let easingControlPoints: [String: [Double]]
    let cases: [CorpusCase]
  }

  private func motionFrameCorpus() throws -> Corpus {
    guard
      let root = try JSONSerialization.jsonObject(
        with: v04FixtureData(named: "motion-frames.json")) as? [String: Any],
      let tolerance = root["toleranceAbsolute"] as? Double,
      let controlPoints = root["easingControlPoints"] as? [String: [Double]],
      let rawCases = root["cases"] as? [[String: Any]]
    else { throw CanonicalFixtureLookupError.invalidShape }

    let cases: [CorpusCase] = try rawCases.map { rawCase in
      guard let id = rawCase["id"] as? String,
        let trigger = rawCase["trigger"] as? String,
        let reducedMotion = rawCase["reducedMotion"] as? Bool,
        let motion = rawCase["motion"] as? [String: Any],
        let rawFrames = rawCase["frames"] as? [[String: Any]]
      else { throw CanonicalFixtureLookupError.invalidShape }

      let frames: [CorpusFrame] = try rawFrames.map { rawFrame in
        guard let elapsed = rawFrame["elapsedMilliseconds"] as? Int,
          let frame = rawFrame["frame"] as? [String: Any],
          let complete = frame["complete"] as? Bool
        else { throw CanonicalFixtureLookupError.invalidShape }
        let values = frame.compactMapValues { $0 as? NSNumber }
          .filter { !($0.value === kCFBooleanTrue || $0.value === kCFBooleanFalse) }
          .mapValues(\.doubleValue)
        return CorpusFrame(
          elapsedMilliseconds: elapsed,
          complete: complete,
          values: values,
          style: try (frame["style"] as? [String: Any]).map {
            try decode(MosaicSelectionStateStyle.self, from: $0, context: id)
          }
        )
      }

      return CorpusCase(
        id: id,
        trigger: trigger,
        reducedMotion: reducedMotion,
        motion: motion,
        resolvedFrom: try (rawCase["resolvedFrom"] as? [String: Any]).map {
          try decode(MosaicSelectionStateStyle.self, from: $0, context: id)
        },
        resolvedTo: try (rawCase["resolvedTo"] as? [String: Any]).map {
          try decode(MosaicSelectionStateStyle.self, from: $0, context: id)
        },
        frames: frames
      )
    }

    return Corpus(
      toleranceAbsolute: tolerance, easingControlPoints: controlPoints, cases: cases)
  }
}
