name: mosaic_sdk
description: Native Protocol 0.1 renderer and Local Preview 0.1 client for Flutter.
version: 0.2.0-dev.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
