/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Studio_layoutRouteImport } from './routes/_studio_layout'
import { Route as HostedRouteImport } from './routes/_hosted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Studio_layoutStudioRouteImport } from './routes/_studio_layout/studio'
import { Route as HostedWorkspaceRouteImport } from './routes/_hosted/workspace'
import { Route as HostedOrganizationsNewRouteImport } from './routes/_hosted/organizations/new'
import { Route as HostedOrganizationsOrganizationIdIndexRouteImport } from './routes/_hosted/organizations/$organizationId/index'
import { Route as HostedOrganizationsOrganizationIdMembersRouteImport } from './routes/_hosted/organizations/$organizationId/members'
import { Route as HostedOrganizationsOrganizationIdProjectsNewRouteImport } from './routes/_hosted/organizations/$organizationId/projects/new'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdIndexRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/index'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdAppsRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/apps'
import { Route as Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRouteImport } from './routes/_studio_layout/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/settings/environments'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/settings/api-keys'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/index'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/index'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/index'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/$productId'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/$planId'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new'
import { Route as HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRouteImport } from './routes/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Studio_layoutRoute = Studio_layoutRouteImport.update({
  id: '/_studio_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedRoute = HostedRouteImport.update({
  id: '/_hosted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Studio_layoutStudioRoute = Studio_layoutStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => Studio_layoutRoute,
} as any)
const HostedWorkspaceRoute = HostedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => HostedRoute,
} as any)
const HostedOrganizationsNewRoute = HostedOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => HostedRoute,
} as any)
const HostedOrganizationsOrganizationIdIndexRoute =
  HostedOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => HostedRoute,
  } as any)
const HostedOrganizationsOrganizationIdMembersRoute =
  HostedOrganizationsOrganizationIdMembersRouteImport.update({
    id: '/organizations/$organizationId/members',
    path: '/organizations/$organizationId/members',
    getParentRoute: () => HostedRoute,
  } as any)
const HostedOrganizationsOrganizationIdProjectsNewRoute =
  HostedOrganizationsOrganizationIdProjectsNewRouteImport.update({
    id: '/organizations/$organizationId/projects/new',
    path: '/organizations/$organizationId/projects/new',
    getParentRoute: () => HostedRoute,
  } as any)
const HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdIndexRouteImport.update({
    id: '/organizations/$organizationId/projects/$projectId/',
    path: '/organizations/$organizationId/projects/$projectId/',
    getParentRoute: () => HostedRoute,
  } as any)
const HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdAppsRouteImport.update({
    id: '/organizations/$organizationId/projects/$projectId/apps',
    path: '/organizations/$organizationId/projects/$projectId/apps',
    getParentRoute: () => HostedRoute,
  } as any)
const Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute =
  Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRouteImport.update(
    {
      id: '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId',
      path: '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId',
      getParentRoute: () => Studio_layoutRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/settings/environments',
      path: '/organizations/$organizationId/projects/$projectId/settings/environments',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/settings/api-keys',
      path: '/organizations/$organizationId/projects/$projectId/settings/api-keys',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/catalog/providers',
      path: '/organizations/$organizationId/projects/$projectId/catalog/providers',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/catalog/products/',
      path: '/organizations/$organizationId/projects/$projectId/catalog/products/',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/catalog/plans/',
      path: '/organizations/$organizationId/projects/$projectId/catalog/plans/',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/catalog/entitlements/',
      path: '/organizations/$organizationId/projects/$projectId/catalog/entitlements/',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases',
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements',
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls',
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments',
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets',
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRouteImport.update(
    {
      id: '/$connectionId',
      path: '/$connectionId',
      getParentRoute: () =>
        HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/catalog/products/$productId',
      path: '/organizations/$organizationId/projects/$projectId/catalog/products/$productId',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId',
      path: '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId',
      path: '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRouteImport.update(
    {
      id: '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface',
      path: '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface',
      getParentRoute: () => HostedRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRouteImport.update(
    {
      id: '/$placementId',
      path: '/$placementId',
      getParentRoute: () =>
        HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRouteImport.update(
    {
      id: '/$paywallId',
      path: '/$paywallId',
      getParentRoute: () =>
        HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRouteImport.update(
    {
      id: '/new',
      path: '/new',
      getParentRoute: () =>
        HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute,
    } as any,
  )
const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRouteImport.update(
    {
      id: '/$experimentId',
      path: '/$experimentId',
      getParentRoute: () =>
        HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof HostedWorkspaceRoute
  '/studio': typeof Studio_layoutStudioRoute
  '/organizations/new': typeof HostedOrganizationsNewRoute
  '/organizations/$organizationId/members': typeof HostedOrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/': typeof HostedOrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/projects/new': typeof HostedOrganizationsOrganizationIdProjectsNewRoute
  '/organizations/$organizationId/projects/$projectId/apps': typeof HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute
  '/organizations/$organizationId/projects/$projectId/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute
  '/organizations/$organizationId/projects/$projectId/catalog/providers': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/settings/api-keys': typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute
  '/organizations/$organizationId/projects/$projectId/settings/environments': typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute
  '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId': typeof Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute
  '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface': typeof HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute
  '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute
  '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute
  '/organizations/$organizationId/projects/$projectId/catalog/products/$productId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute
  '/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute
  '/organizations/$organizationId/projects/$projectId/catalog/entitlements/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute
  '/organizations/$organizationId/projects/$projectId/catalog/plans/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute
  '/organizations/$organizationId/projects/$projectId/catalog/products/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof HostedWorkspaceRoute
  '/studio': typeof Studio_layoutStudioRoute
  '/organizations/new': typeof HostedOrganizationsNewRoute
  '/organizations/$organizationId/members': typeof HostedOrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId': typeof HostedOrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/projects/new': typeof HostedOrganizationsOrganizationIdProjectsNewRoute
  '/organizations/$organizationId/projects/$projectId/apps': typeof HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute
  '/organizations/$organizationId/projects/$projectId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute
  '/organizations/$organizationId/projects/$projectId/catalog/providers': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/settings/api-keys': typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute
  '/organizations/$organizationId/projects/$projectId/settings/environments': typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute
  '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId': typeof Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute
  '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface': typeof HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute
  '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute
  '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute
  '/organizations/$organizationId/projects/$projectId/catalog/products/$productId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute
  '/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute
  '/organizations/$organizationId/projects/$projectId/catalog/entitlements': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute
  '/organizations/$organizationId/projects/$projectId/catalog/plans': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute
  '/organizations/$organizationId/projects/$projectId/catalog/products': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute
  '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hosted': typeof HostedRouteWithChildren
  '/_studio_layout': typeof Studio_layoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_hosted/workspace': typeof HostedWorkspaceRoute
  '/_studio_layout/studio': typeof Studio_layoutStudioRoute
  '/_hosted/organizations/new': typeof HostedOrganizationsNewRoute
  '/_hosted/organizations/$organizationId/members': typeof HostedOrganizationsOrganizationIdMembersRoute
  '/_hosted/organizations/$organizationId/': typeof HostedOrganizationsOrganizationIdIndexRoute
  '/_hosted/organizations/$organizationId/projects/new': typeof HostedOrganizationsOrganizationIdProjectsNewRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/apps': typeof HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteWithChildren
  '/_hosted/organizations/$organizationId/projects/$projectId/settings/api-keys': typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/settings/environments': typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute
  '/_studio_layout/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId': typeof Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface': typeof HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/$planId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/$productId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteWithChildren
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteWithChildren
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteWithChildren
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/': typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute
  '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId': typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/studio'
    | '/organizations/new'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/projects/new'
    | '/organizations/$organizationId/projects/$projectId/apps'
    | '/organizations/$organizationId/projects/$projectId/'
    | '/organizations/$organizationId/projects/$projectId/catalog/providers'
    | '/organizations/$organizationId/projects/$projectId/settings/api-keys'
    | '/organizations/$organizationId/projects/$projectId/settings/environments'
    | '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId'
    | '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface'
    | '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId'
    | '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId'
    | '/organizations/$organizationId/projects/$projectId/catalog/products/$productId'
    | '/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases'
    | '/organizations/$organizationId/projects/$projectId/catalog/entitlements/'
    | '/organizations/$organizationId/projects/$projectId/catalog/plans/'
    | '/organizations/$organizationId/projects/$projectId/catalog/products/'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/studio'
    | '/organizations/new'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/projects/new'
    | '/organizations/$organizationId/projects/$projectId/apps'
    | '/organizations/$organizationId/projects/$projectId'
    | '/organizations/$organizationId/projects/$projectId/catalog/providers'
    | '/organizations/$organizationId/projects/$projectId/settings/api-keys'
    | '/organizations/$organizationId/projects/$projectId/settings/environments'
    | '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId'
    | '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface'
    | '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId'
    | '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId'
    | '/organizations/$organizationId/projects/$projectId/catalog/products/$productId'
    | '/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases'
    | '/organizations/$organizationId/projects/$projectId/catalog/entitlements'
    | '/organizations/$organizationId/projects/$projectId/catalog/plans'
    | '/organizations/$organizationId/projects/$projectId/catalog/products'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId'
    | '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId'
  id:
    | '__root__'
    | '/'
    | '/_hosted'
    | '/_studio_layout'
    | '/login'
    | '/signup'
    | '/_hosted/workspace'
    | '/_studio_layout/studio'
    | '/_hosted/organizations/new'
    | '/_hosted/organizations/$organizationId/members'
    | '/_hosted/organizations/$organizationId/'
    | '/_hosted/organizations/$organizationId/projects/new'
    | '/_hosted/organizations/$organizationId/projects/$projectId/apps'
    | '/_hosted/organizations/$organizationId/projects/$projectId/'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers'
    | '/_hosted/organizations/$organizationId/projects/$projectId/settings/api-keys'
    | '/_hosted/organizations/$organizationId/projects/$projectId/settings/environments'
    | '/_studio_layout/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId'
    | '/_hosted/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/$planId'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/$productId'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/'
    | '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId'
    | '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostedRoute: typeof HostedRouteWithChildren
  Studio_layoutRoute: typeof Studio_layoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio_layout': {
      id: '/_studio_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Studio_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hosted': {
      id: '/_hosted'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HostedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio_layout/studio': {
      id: '/_studio_layout/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof Studio_layoutStudioRouteImport
      parentRoute: typeof Studio_layoutRoute
    }
    '/_hosted/workspace': {
      id: '/_hosted/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof HostedWorkspaceRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/new': {
      id: '/_hosted/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof HostedOrganizationsNewRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/': {
      id: '/_hosted/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/members': {
      id: '/_hosted/organizations/$organizationId/members'
      path: '/organizations/$organizationId/members'
      fullPath: '/organizations/$organizationId/members'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdMembersRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/new': {
      id: '/_hosted/organizations/$organizationId/projects/new'
      path: '/organizations/$organizationId/projects/new'
      fullPath: '/organizations/$organizationId/projects/new'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsNewRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/'
      path: '/organizations/$organizationId/projects/$projectId'
      fullPath: '/organizations/$organizationId/projects/$projectId/'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/apps': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/apps'
      path: '/organizations/$organizationId/projects/$projectId/apps'
      fullPath: '/organizations/$organizationId/projects/$projectId/apps'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdAppsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_studio_layout/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId': {
      id: '/_studio_layout/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId'
      path: '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId'
      fullPath: '/studio-hosted/$organizationId/$projectId/$environmentId/$paywallId/$draftId'
      preLoaderRoute: typeof Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRouteImport
      parentRoute: typeof Studio_layoutRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/settings/environments': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/settings/environments'
      path: '/organizations/$organizationId/projects/$projectId/settings/environments'
      fullPath: '/organizations/$organizationId/projects/$projectId/settings/environments'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/settings/api-keys': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/settings/api-keys'
      path: '/organizations/$organizationId/projects/$projectId/settings/api-keys'
      fullPath: '/organizations/$organizationId/projects/$projectId/settings/api-keys'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers'
      path: '/organizations/$organizationId/projects/$projectId/catalog/providers'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/providers'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/'
      path: '/organizations/$organizationId/projects/$projectId/catalog/products'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/products/'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/'
      path: '/organizations/$organizationId/projects/$projectId/catalog/plans'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/plans/'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/'
      path: '/organizations/$organizationId/projects/$projectId/catalog/entitlements'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/entitlements/'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases'
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/releases'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements'
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls'
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments'
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets'
      path: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/assets'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId'
      path: '/$connectionId'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/providers/$connectionId'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRouteImport
      parentRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/$productId': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/products/$productId'
      path: '/organizations/$organizationId/projects/$projectId/catalog/products/$productId'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/products/$productId'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/$planId': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/plans/$planId'
      path: '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/plans/$planId'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId'
      path: '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId'
      fullPath: '/organizations/$organizationId/projects/$projectId/catalog/entitlements/$entitlementId'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface'
      path: '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface'
      fullPath: '/organizations/$organizationId/projects/$projectId/analytics/$environmentId/$surface'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRouteImport
      parentRoute: typeof HostedRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId'
      path: '/$placementId'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/placements/$placementId'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRouteImport
      parentRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId'
      path: '/$paywallId'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/paywalls/$paywallId'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRouteImport
      parentRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new'
      path: '/new'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/new'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRouteImport
      parentRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute
    }
    '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId': {
      id: '/_hosted/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/organizations/$organizationId/projects/$projectId/monetization/$environmentId/experiments/$experimentId'
      preLoaderRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRouteImport
      parentRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute
    }
  }
}

interface HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteChildren {
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute
}

const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteChildren: HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteChildren =
  {
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute:
      HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersConnectionIdRoute,
  }

const HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteWithChildren =
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRoute._addFileChildren(
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteChildren,
  )

interface HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteChildren {
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute
}

const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteChildren: HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteChildren =
  {
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute:
      HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsExperimentIdRoute,
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute:
      HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsNewRoute,
  }

const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteWithChildren =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute._addFileChildren(
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteChildren,
  )

interface HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteChildren {
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute
}

const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteChildren: HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteChildren =
  {
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute:
      HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsPaywallIdRoute,
  }

const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteWithChildren =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRoute._addFileChildren(
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteChildren,
  )

interface HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteChildren {
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute
}

const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteChildren: HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteChildren =
  {
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute:
      HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsPlacementIdRoute,
  }

const HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteWithChildren =
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRoute._addFileChildren(
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteChildren,
  )

interface HostedRouteChildren {
  HostedWorkspaceRoute: typeof HostedWorkspaceRoute
  HostedOrganizationsNewRoute: typeof HostedOrganizationsNewRoute
  HostedOrganizationsOrganizationIdMembersRoute: typeof HostedOrganizationsOrganizationIdMembersRoute
  HostedOrganizationsOrganizationIdIndexRoute: typeof HostedOrganizationsOrganizationIdIndexRoute
  HostedOrganizationsOrganizationIdProjectsNewRoute: typeof HostedOrganizationsOrganizationIdProjectsNewRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteWithChildren
  HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteWithChildren
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteWithChildren
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteWithChildren
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute: typeof HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute
}

const HostedRouteChildren: HostedRouteChildren = {
  HostedWorkspaceRoute: HostedWorkspaceRoute,
  HostedOrganizationsNewRoute: HostedOrganizationsNewRoute,
  HostedOrganizationsOrganizationIdMembersRoute:
    HostedOrganizationsOrganizationIdMembersRoute,
  HostedOrganizationsOrganizationIdIndexRoute:
    HostedOrganizationsOrganizationIdIndexRoute,
  HostedOrganizationsOrganizationIdProjectsNewRoute:
    HostedOrganizationsOrganizationIdProjectsNewRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdAppsRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdIndexRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProvidersRouteWithChildren,
  HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdSettingsApiKeysRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdSettingsEnvironmentsRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdAnalyticsEnvironmentIdSurfaceRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsEntitlementIdRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansPlanIdRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsProductIdRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdAssetsRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdExperimentsRouteWithChildren,
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPaywallsRouteWithChildren,
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdPlacementsRouteWithChildren,
  HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdMonetizationEnvironmentIdReleasesRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogEntitlementsIndexRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogPlansIndexRoute,
  HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute:
    HostedOrganizationsOrganizationIdProjectsProjectIdCatalogProductsIndexRoute,
}

const HostedRouteWithChildren =
  HostedRoute._addFileChildren(HostedRouteChildren)

interface Studio_layoutRouteChildren {
  Studio_layoutStudioRoute: typeof Studio_layoutStudioRoute
  Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute: typeof Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute
}

const Studio_layoutRouteChildren: Studio_layoutRouteChildren = {
  Studio_layoutStudioRoute: Studio_layoutStudioRoute,
  Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute:
    Studio_layoutStudioHostedOrganizationIdProjectIdEnvironmentIdPaywallIdDraftIdRoute,
}

const Studio_layoutRouteWithChildren = Studio_layoutRoute._addFileChildren(
  Studio_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostedRoute: HostedRouteWithChildren,
  Studio_layoutRoute: Studio_layoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
