package billing

import (
	"context"
	"time"
)

// ListOptions is the shared cursor-pagination shape for billing reads.
type ListOptions struct {
	Limit  int
	Cursor string
	// Filters are closed sets validated at the transport boundary before they
	// reach SQL.
	Status     string
	ReasonCode string
	Provider   string
	From       *time.Time
	To         *time.Time
}

// Page is one page of results plus the cursor for the next.
type Page[T any] struct {
	Items      []T    `json:"items"`
	NextCursor string `json:"nextCursor,omitempty"`
}

// CredentialInput is a create or rotate request. Secret is the raw .p8 PEM or
// service-account JSON and is zeroed by the service once sealed.
type CredentialInput struct {
	// CredentialID is generated by the service before encryption, because the
	// envelope's additional data binds the ciphertext to this exact row.
	CredentialID             string
	ProjectID                string
	EnvironmentID            string
	Provider                 string
	StoreEnvironment         string
	Name                     string
	Secret                   []byte
	AppleIssuerID            string
	AppleKeyID               string
	GoogleClientEmail        string
	GooglePubSubProjectID    string
	GooglePubSubSubscription string
	Applications             []CredentialApplication
}

// IntakeIdentity is what an Apple intake token resolves to. It is deliberately
// minimal: the intake path must be a single indexed read before any body is
// parsed.
type IntakeIdentity struct {
	CredentialID     string
	ProjectID        string
	OrganizationID   string
	EnvironmentID    string
	EnvironmentMode  string
	StoreEnvironment string
	Provider         string
	Status           string
}

// PersistResult reports what an idempotent raw-input write actually did.
type PersistResult struct {
	RawInputID string
	Status     string
	// Conflicted is set when the idempotency key already existed with a
	// different content digest, which is evidence of either a provider bug or a
	// forgery attempt and always quarantines.
	Conflicted bool
	Enqueued   bool
}

// AttemptOutcome is everything one validation attempt produced, written in one
// transaction so an attempt, its resolution, its fact, its ledger entries, and
// its queue transition can never disagree.
type AttemptOutcome struct {
	Attempt    ValidationAttempt
	Resolution *ResolutionRecord
	Fact       *TransactionFact
	Ledger     []LedgerEntry
	Quarantine *QuarantineWrite
	// NextAvailableAt schedules a retry; zero completes or fails the job.
	NextAvailableAt time.Time
	JobStatus       string
}

// ResolutionRecord is the persisted Resolution Snapshot.
type ResolutionRecord struct {
	ID                         string
	ProjectID                  string
	EnvironmentID              string
	ApplicationID              string
	ValidationAttemptID        string
	RawInputID                 string
	Provider                   string
	ProviderProductIdentifier  string
	ProviderBasePlanIdentifier string
	ProviderOfferIdentifier    string
	Outcome                    string
	ResolutionState            string
	MosaicProductID            string
	ProviderProductMappingID   string
	MatchedMappingID           string
	MappingVersion             *int64
	CandidateCount             int
	DiagnosticCode             string
	OccurredAt                 time.Time
	ResolvedAt                 time.Time
}

// QuarantineWrite opens or updates a quarantine record.
type QuarantineWrite struct {
	RawInputID     string
	ApplicationID  string
	Provider       string
	ReasonCode     string
	Severity       string
	Scopes         []string
	DiagnosticCode string
	OccurredAt     time.Time
}

// Repository is the persistence port. Authorization for operator-facing reads
// and writes is enforced in SQL alongside the query, following the analytics
// precedent, so no caller can reach a tenant's billing data by forgetting a
// check.
type Repository interface {
	// Settings and tenancy.
	BillingEnabled(ctx context.Context, projectID string) (bool, error)
	OrganizationForProject(ctx context.Context, projectID string) (string, error)
	SetBillingEnabled(ctx context.Context, actor Actor, projectID string, enabled bool, now time.Time) error

	// Credentials.
	CreateCredential(ctx context.Context, actor Actor, input CredentialInput, envelope Envelope, class string, intakeTokenDigest []byte, now time.Time) (StoreServerCredential, error)
	RotateCredential(ctx context.Context, actor Actor, projectID, credentialID string, envelope Envelope, intakeTokenDigest []byte, now time.Time) (StoreServerCredential, error)
	RevokeCredential(ctx context.Context, actor Actor, projectID, credentialID string, now time.Time) (StoreServerCredential, error)
	ListCredentials(ctx context.Context, actor Actor, projectID string) ([]StoreServerCredential, error)
	GetCredential(ctx context.Context, actor Actor, projectID, credentialID string) (StoreServerCredential, error)
	// CredentialSecretFor decrypts through the supplied opener. The repository
	// owns the envelope columns; the service owns the cipher.
	CredentialSecretFor(ctx context.Context, projectID, credentialID string) (StoreServerCredential, Envelope, string, string, string, error)
	CredentialForApplication(ctx context.Context, environmentID, provider, providerApplicationIdentifier string) (IntakeIdentity, string, error)
	RecordCredentialEvent(ctx context.Context, projectID, credentialID, action, outcome, diagnosticCode, actorID string, now time.Time) error
	UpdateCredentialHealth(ctx context.Context, projectID, credentialID, health, errorCode string, tested bool, now time.Time) error
	// ActiveCredentials lists every usable credential for the worker loops.
	ActiveCredentials(ctx context.Context, provider string) ([]IntakeIdentity, error)

	// Intake.
	ResolveIntakeToken(ctx context.Context, tokenDigest []byte) (IntakeIdentity, error)
	PersistRawInput(ctx context.Context, input RawInput, enqueue bool, now time.Time) (PersistResult, error)
	RawInput(ctx context.Context, projectID, rawInputID string) (RawInput, error)
	// ApplicationForIdentifier maps a verified bundle id or package name onto an
	// Application inside the credential's scope.
	ApplicationForIdentifier(ctx context.Context, credentialID, identifier string) (string, string, error)

	// Observations.
	AuthenticateSDKKey(ctx context.Context, raw string) (ObservationScope, error)
	AuthenticateServerKey(ctx context.Context, raw string) (ObservationScope, error)

	// Validation worker.
	LeaseValidationJob(ctx context.Context, workerID string, now, leaseUntil time.Time) (ValidationJob, bool, error)
	CompleteAttempt(ctx context.Context, job ValidationJob, outcome AttemptOutcome, now time.Time) error
	NextAttemptNumber(ctx context.Context, rawInputID string) (int, error)

	// Resolution.
	MappingCandidates(ctx context.Context, environmentID, applicationID, platform, provider, providerProductIdentifier string) ([]MappingCandidate, error)
	MappingSuccessors(ctx context.Context, projectID string, mappingIDs []string) (map[string]MappingCandidate, error)

	// Reads.
	ListFacts(ctx context.Context, actor Actor, projectID, environmentID string, options ListOptions) (Page[TransactionFact], error)
	ListAttempts(ctx context.Context, actor Actor, projectID, environmentID string, options ListOptions) (Page[ValidationAttempt], error)
	ListLedger(ctx context.Context, actor Actor, projectID, environmentID string, options ListOptions) (Page[LedgerEntry], error)
	ListQuarantine(ctx context.Context, actor Actor, projectID, environmentID string, options ListOptions) (Page[QuarantineRecord], error)
	Quarantine(ctx context.Context, actor Actor, projectID, recordID string) (QuarantineRecord, error)

	// Recovery actions.
	RequeueValidation(ctx context.Context, actor Actor, projectID, recordID string, now time.Time) (QuarantineRecord, error)
	CloseQuarantineSuperseded(ctx context.Context, actor Actor, projectID, recordID, supersededBy string, now time.Time) (QuarantineRecord, error)

	// Reconciliation and replay.
	CreateReconciliationRun(ctx context.Context, actor Actor, run ReconciliationRun, now time.Time) (ReconciliationRun, error)
	ListReconciliationRuns(ctx context.Context, actor Actor, projectID, environmentID string, options ListOptions) (Page[ReconciliationRun], error)
	LeaseReconciliationRun(ctx context.Context, workerID string, now, leaseUntil time.Time) (ReconciliationRun, bool, error)
	UpdateReconciliationProgress(ctx context.Context, run ReconciliationRun, cursorToken string, now time.Time) error
	CompleteReconciliationRun(ctx context.Context, run ReconciliationRun, status, errorCode string, now time.Time) error

	CreateReplayJob(ctx context.Context, actor Actor, job ReplayJob, now time.Time) (ReplayJob, error)
	ListReplayJobs(ctx context.Context, actor Actor, projectID, environmentID string, options ListOptions) (Page[ReplayJob], error)
	LeaseReplayJob(ctx context.Context, workerID string, now, leaseUntil time.Time) (ReplayJob, bool, error)
	ReplayInputs(ctx context.Context, job ReplayJob, limit int) ([]RawInput, error)
	CompleteReplayJob(ctx context.Context, job ReplayJob, comparison, errorCode string, now time.Time) error

	// Retention. The only path that removes a raw body.
	ExpireRawInputBodies(ctx context.Context, now time.Time, limit int) (int64, error)

	// Health.
	Health(ctx context.Context, actor Actor, projectID, environmentID string) (Health, error)
}

// Health is the billing health summary shown to operators.
type Health struct {
	EnvironmentID        string     `json:"environmentId"`
	BillingEnabled       bool       `json:"billingEnabled"`
	CredentialCount      int        `json:"credentialCount"`
	UnhealthyCredentials int        `json:"unhealthyCredentials"`
	QueueDepth           int64      `json:"queueDepth"`
	OldestQueuedAgeSecs  float64    `json:"oldestQueuedAgeSeconds"`
	OpenQuarantineCount  int64      `json:"openQuarantineCount"`
	FactCount            int64      `json:"factCount"`
	LastFactRecordedAt   *time.Time `json:"lastFactRecordedAt,omitempty"`
	LastReconciliationAt *time.Time `json:"lastReconciliationAt,omitempty"`
}
