package dev.mosaic.sdk

import com.google.gson.JsonObject
import com.google.gson.JsonParser
import java.nio.file.Files
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.text.Charsets

/**
 * Every frame in `protocol/fixtures/v0.4/motion-frames.json`, driven through this SDK's resolver.
 *
 * Motion is the first thing in the protocol whose contract is *a value at an instant* rather than a
 * value; prose cannot pin that and three renderers will not agree by coincidence. The vectors are
 * generated by `resolveV04MotionFrame` and reconciled against it by the protocol gate, so this is
 * the assertion that the Kotlin renderer produces the same numbers as the reference — not that it
 * produces numbers that look plausible.
 *
 * The corpus is read whole and its size asserted: a truncated or partially-parsed fixture would
 * otherwise report perfect conformance over nothing.
 */
class MotionFrameConformanceTest {
    @Test
    fun everyRecordedFrameMatchesTheReferenceResolverWithinTolerance() {
        val vectors = motionFrameVectors()
        val tolerance = vectors.get("toleranceAbsolute").asDouble
        assertEquals(0.001, tolerance, 0.0)

        val cases = vectors.getAsJsonArray("cases")
        var frameCount = 0
        val triggers = mutableSetOf<String>()
        val easings = mutableSetOf<String>()
        val reduced = mutableSetOf<Boolean>()

        cases.forEach { element ->
            val entry = element.asJsonObject
            val id = entry.get("id").asString
            val trigger = entry.get("trigger").asString
            val reducedMotion = entry.get("reducedMotion").asBoolean
            val motion = entry.getAsJsonObject("motion")
            triggers += trigger
            easings += motion.getAsJsonObject("curve").get("easing").asString
            reduced += reducedMotion

            val frames = entry.getAsJsonArray("frames")
            assertTrue("$id pins fewer than five frames", frames.size() >= 5)
            frames.forEach { frameElement ->
                frameCount += 1
                val recorded = frameElement.asJsonObject
                val elapsed = recorded.get("elapsedMilliseconds").asLong
                val expected = recorded.getAsJsonObject("frame")
                when (trigger) {
                    "appear" -> assertAppearFrame(id, motion, elapsed, reducedMotion, expected, tolerance)
                    "selection" -> assertSelectionFrame(
                        id,
                        motion,
                        elapsed,
                        reducedMotion,
                        entry.getAsJsonObject("resolvedFrom"),
                        entry.getAsJsonObject("resolvedTo"),
                        expected,
                        tolerance,
                    )
                    "loop" -> assertLoopFrame(id, motion, elapsed, reducedMotion, expected, tolerance)
                    else -> error("Unknown Protocol 0.4 motion trigger $trigger in case $id.")
                }
            }

            // The last frame of every case is the terminal state; a case that never reaches it
            // leaves the rule that makes renderWithoutMotion lossless unexercised.
            assertTrue(
                "$id never reaches its terminal state",
                frames.last().asJsonObject.getAsJsonObject("frame").get("complete").asBoolean,
            )
        }

        assertEquals(EXPECTED_CASE_COUNT, cases.size())
        assertEquals(EXPECTED_FRAME_COUNT, frameCount)
        assertEquals(setOf("appear", "selection", "loop"), triggers)
        assertEquals(
            MosaicMotionEasing.entries.mapTo(mutableSetOf(), MosaicMotionEasing::wireName),
            easings,
        )
        assertEquals(setOf(false, true), reduced)
    }

    /**
     * The presets a renderer actually draws with must be the presets the vectors were generated
     * from. The frame values above come from this SDK's own solver; this is what says the Compose
     * curve the contract names is the same curve, rather than a second opinion about it.
     */
    @Test
    fun composeEasingCurvesMatchTheNormativeControlPoints() {
        val recorded = motionFrameVectors().getAsJsonObject("easingControlPoints")
        MosaicMotionEasing.entries.forEach { easing ->
            val points = recorded.getAsJsonArray(easing.wireName).map { it.asDouble }
            assertEquals(
                "${easing.wireName} control points",
                points,
                listOf(
                    easing.controlPointX1,
                    easing.controlPointY1,
                    easing.controlPointX2,
                    easing.controlPointY2,
                ),
            )
            val compose = easing.toComposeEasing()
            (0..100).forEach { step ->
                val fraction = step / 100.0
                assertEquals(
                    "${easing.wireName} at $fraction",
                    MosaicMotionFrames.easedProgress(easing, fraction),
                    compose.transform(fraction.toFloat()).toDouble(),
                    TOLERANCE,
                )
            }
        }
    }

    /**
     * `appear` and `loop` on one Button share a time origin: node entry.
     *
     * No canonical case pins two primitives on one node, so nothing else here would notice a
     * refactor that started the pulse only once the entrance had finished — the terminal state
     * would still be correct and every single-primitive vector would still pass. The instant that
     * distinguishes the two readings is a frame *inside the entrance*: with a shared origin the
     * pulse is already mid-excursion there, and with a gated one it would be exactly at rest.
     */
    @Test
    fun appearAndLoopOnOneNodeShareTheNodeEntryTimeOrigin() {
        // The canonical fixture's purchase Button: a 240ms entrance held behind a 240ms delay, and
        // a 900ms pulse repeated three times.
        val appear = MosaicAppearMotion(
            effect = MosaicAppearEffect.FADE,
            curve = MosaicMotion(240, MosaicMotionEasing.DECELERATE),
            delayMilliseconds = 240,
        )
        val loop = MosaicLoopMotion(
            scaleAmplitude = 0.04,
            opacityAmplitude = 0.12,
            curve = MosaicMotion(900, MosaicMotionEasing.STANDARD),
            repeatCount = 3,
        )

        // 360ms in: the entrance is half way through its curve, and the pulse -- which started at
        // node entry, not at the end of the entrance -- is 40% through its first cycle.
        val midEntrance = 360L
        val appearFrame = MosaicMotionFrames.appear(appear, midEntrance, reducedMotion = false)
        val loopFrame = MosaicMotionFrames.loop(loop, midEntrance, reducedMotion = false)

        assertTrue("The entrance must still be running.", !appearFrame.complete)
        assertTrue("The entrance must be part way through.", appearFrame.opacity in 0.001..0.999)
        assertEquals("The pulse must be in its first cycle.", 0, loopFrame.cycle)
        assertEquals(0.4, loopFrame.cyclePhase, TOLERANCE)
        // The assertion a gated pulse fails: at rest these would be exactly 1.0.
        assertTrue("The pulse must already be scaling mid-entrance.", loopFrame.scale > 1.0)
        assertTrue("The pulse must already be dimming mid-entrance.", loopFrame.opacityMultiplier < 1.0)

        // opacity = static x appearProgress x loopOpacityMultiplier, scale = loopScale.
        val composed = MosaicMotionFrames.composed(appearFrame, loopFrame)
        assertEquals(
            appearFrame.opacity * loopFrame.opacityMultiplier,
            composed.opacityMultiplier,
            TOLERANCE,
        )
        assertEquals(loopFrame.scale, composed.scale, TOLERANCE)
        assertEquals(appearFrame.translateLogicalSize, composed.translateLogicalSize, TOLERANCE)
        assertTrue("A composed mid-flight frame is not the static rendering.", !composed.isStatic)

        // Both primitives finished: the composition is the static rendering exactly, which is what
        // lets the renderer drop its layer rather than keep one at identity values.
        val terminal = MosaicMotionFrames.composed(
            MosaicMotionFrames.appear(appear, 10_000L, reducedMotion = false)
                .takeUnless(MosaicAppearFrame::complete),
            MosaicMotionFrames.loop(loop, 10_000L, reducedMotion = false)
                .takeUnless(MosaicLoopFrame::complete),
        )
        assertEquals(MosaicMotionComposition.Static, terminal)
        assertTrue(terminal.isStatic)
    }

    private fun assertAppearFrame(
        id: String,
        motion: JsonObject,
        elapsed: Long,
        reducedMotion: Boolean,
        expected: JsonObject,
        tolerance: Double,
    ) {
        val actual = MosaicMotionFrames.appear(appearMotion(motion, "$.motion"), elapsed, reducedMotion)
        val label = "$id at ${elapsed}ms"
        assertEquals(label, expected.get("complete").asBoolean, actual.complete)
        assertEquals(label, expected.get("progress").asDouble, actual.progress, tolerance)
        assertEquals(label, expected.get("opacity").asDouble, actual.opacity, tolerance)
        assertEquals(
            label,
            expected.get("translateLogicalSize").asDouble,
            actual.translateLogicalSize,
            tolerance,
        )
    }

    private fun assertLoopFrame(
        id: String,
        motion: JsonObject,
        elapsed: Long,
        reducedMotion: Boolean,
        expected: JsonObject,
        tolerance: Double,
    ) {
        val actual = MosaicMotionFrames.loop(loopMotion(motion, "$.motion"), elapsed, reducedMotion)
        val label = "$id at ${elapsed}ms"
        assertEquals(label, expected.get("complete").asBoolean, actual.complete)
        assertEquals(label, expected.get("cycle").asInt, actual.cycle)
        assertEquals(label, expected.get("cyclePhase").asDouble, actual.cyclePhase, tolerance)
        assertEquals(label, expected.get("excursion").asDouble, actual.excursion, tolerance)
        assertEquals(label, expected.get("scale").asDouble, actual.scale, tolerance)
        assertEquals(
            label,
            expected.get("opacityMultiplier").asDouble,
            actual.opacityMultiplier,
            tolerance,
        )
    }

    private fun assertSelectionFrame(
        id: String,
        motion: JsonObject,
        elapsed: Long,
        reducedMotion: Boolean,
        from: JsonObject,
        to: JsonObject,
        expected: JsonObject,
        tolerance: Double,
    ) {
        val actual = MosaicMotionFrames.selection(
            selectionMotion(motion, "$.motion"),
            elapsed,
            reducedMotion,
            selectionStateStyle(from, "$.resolvedFrom"),
            selectionStateStyle(to, "$.resolvedTo"),
        )
        val label = "$id at ${elapsed}ms"
        assertEquals(label, expected.get("complete").asBoolean, actual.complete)
        assertEquals(label, expected.get("progress").asDouble, actual.progress, tolerance)

        val style = expected.getAsJsonObject("style")
        val expectedStyle = selectionStateStyle(style, "$.frame.style")
        // Colours are compared as canonical literals rather than as channel numbers: the contract
        // emits `#RRGGBBAA`, and a renderer that rounded a channel differently would produce a
        // different literal, which is exactly the divergence worth catching.
        assertEquals(label, expectedStyle.background, actual.style.background)
        assertEquals(label, expectedStyle.border.color, actual.style.border.color)
        assertEquals(label, expectedStyle.border.width, actual.style.border.width, tolerance)
        assertEquals(label, expectedStyle.cornerRadius, actual.style.cornerRadius, tolerance)
        assertEquals(label, expectedStyle.opacity, actual.style.opacity, tolerance)
        // Padding is structural and switches discretely at the half-way point.
        assertEquals(label, expectedStyle.padding, actual.style.padding)
        assertEquals(label, expectedStyle.shadow?.color, actual.style.shadow?.color)
        assertEquals(label, expectedStyle.shadow?.offsetY, actual.style.shadow?.offsetY)
        assertEquals(label, expectedStyle.shadow?.blurRadius, actual.style.shadow?.blurRadius)
    }

    private fun motionFrameVectors(): JsonObject {
        val path = repositoryFile("protocol/fixtures/v0.4/motion-frames.json")
        val source = Files.readAllBytes(path).toString(Charsets.UTF_8)
        return JsonParser.parseString(source).asJsonObject
    }

    private companion object {
        const val TOLERANCE = 0.001

        /**
         * Pinned so a fixture that shrinks fails here rather than quietly narrowing what this SDK
         * claims to conform to.
         */
        const val EXPECTED_CASE_COUNT = 45
        const val EXPECTED_FRAME_COUNT = 229
    }
}
